# Generated by Django 4.2.5 on 2023-09-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_current_day_person_utc_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='day',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
