# Generated by Django 4.2.5 on 2023-09-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_person_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.IntegerField(default=200),
        ),
    ]
